apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ola-mundo-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ola-mundo-v2
  template:
    metadata:
      labels:
        app: nginx-ola-mundo-v2
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: nginx-ola-mundo-v2
        image: marcelosales/nginx-ola-mundo:v2-20250710-1517
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5