name: Build e Push Docker Image

on:
  push:
    branches:
      - v2

jobs:
  build and deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Login no DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build da Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-ola-mundo:2.0 ./app

    - name: Push da Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-ola-mundo:2.0

