name: Build, Tag, Push Docker Image e update Deployment
# Descrição: Este workflow é acionado quando há um push na branch v2. Ele constrói uma imagem Docker, faz o push para o DockerHub e atualiza o arquivo deployment.yaml com a nova tag da imagem.

on:
  push:
    branches:
      - v2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Definir TAG da imagem (timestamp)
      id: vars
      run: echo "IMAGE_TAG=v2-$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

    - name: Login no DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build da Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-ola-mundo:${{ env.IMAGE_TAG }} ./app
        docker tag ${{ secrets.DOCKER_USERNAME }}/nginx-ola-mundo:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/nginx-ola-mundo:latest

    - name: Push da Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx-ola-mundo:${{ env.IMAGE_TAG }}
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx-ola-mundo:latest



